spring:
  liquibase:
    enabled: false
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/postgres?user=${DB_USER_RW}&password=${DB_PWD_RW}
    username: ${DB_USER_RW}
    password: ${DB_PWD_RW}
